import React from 'react';
import LegalLayout, { LegalSection } from './LegalLayout';

const sections: LegalSection[] = [
  {
    id: 'acceptance',
    title: '1. Acceptance of Terms',
    content: (
      <p>
        By accessing or using StoryVerse (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please
        do not use our Service.
      </p>
    ),
  },
  {
    id: 'description',
    title: '2. Description of Service',
    content: (
      <p>
        StoryVerse is an AI-powered screenwriting application that provides tools for story development, script writing, and creative collaboration with
        artificial intelligence.
      </p>
    ),
  },
  {
    id: 'accounts',
    title: '3. User Accounts',
    content: (
      <ul>
        <li>You must provide accurate and complete registration information</li>
        <li>You are responsible for maintaining the security of your account</li>
        <li>You must be at least 13 years old to use this Service</li>
        <li>One person may not maintain more than one account</li>
        <li>You are responsible for all activity that occurs under your account</li>
      </ul>
    ),
  },
  {
    id: 'content',
    title: '4. User Content',
    content: (
      <>
        <h3>4.1 Ownership</h3>
        <p>You retain all rights to the content you create using StoryVerse, including scripts, characters, and story materials.</p>
        <h3>4.2 License to Us</h3>
        <p>By using the Service, you grant us a limited license to process your content solely for the purpose of providing the Service to you.</p>
        <h3>4.3 AI-Generated Content</h3>
        <p>Content generated by our AI features is provided for your use. You may use AI-generated content in your projects, subject to applicable laws.</p>
      </>
    ),
  },
  {
    id: 'acceptable-use',
    title: '5. Acceptable Use',
    content: (
      <>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service for any illegal purpose</li>
          <li>Generate content that is harmful, abusive, or violates others' rights</li>
          <li>Attempt to bypass any security measures</li>
          <li>Use automated systems to access the Service without permission</li>
          <li>Interfere with or disrupt the Service</li>
          <li>Resell or redistribute the Service without authorization</li>
        </ul>
      </>
    ),
  },
  {
    id: 'subscriptions',
    title: '6. Subscription and Payment',
    content: (
      <>
        <h3>6.1 Free Tier</h3>
        <p>The free tier includes limited features and usage quotas as described on our pricing page.</p>
        <h3>6.2 Paid Plans</h3>
        <p>Paid subscriptions are billed monthly or annually. Prices are subject to change with 30 days notice.</p>
        <h3>6.3 Cancellation</h3>
        <p>You may cancel your subscription at any time. Access continues until the end of your billing period.</p>
      </>
    ),
  },
  {
    id: 'ip',
    title: '7. Intellectual Property',
    content: (
      <p>The Service, including its design, features, and content (excluding user-generated content), is owned by StoryVerse and protected by law.</p>
    ),
  },
  {
    id: 'warranties',
    title: '8. Disclaimer of Warranties',
    content: (
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND. WE DO NOT GUARANTEE THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR
        SECURE.
      </p>
    ),
  },
  {
    id: 'liability',
    title: '9. Limitation of Liability',
    content: (
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, STORYVERSE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM
        YOUR USE OF THE SERVICE.
      </p>
    ),
  },
  {
    id: 'termination',
    title: '10. Termination',
    content: (
      <p>
        We may terminate or suspend your account at any time for violation of these terms. Upon termination, your right to use the Service will immediately
        cease.
      </p>
    ),
  },
  {
    id: 'changes',
    title: '11. Changes to Terms',
    content: (
      <p>
        We reserve the right to modify these terms at any time. We will provide notice of significant changes. Continued use of the Service constitutes
        acceptance of modified terms.
      </p>
    ),
  },
  {
    id: 'law',
    title: '12. Governing Law',
    content: (
      <p>These Terms shall be governed by the laws of the Federal Republic of Germany, without regard to conflict of law principles.</p>
    ),
  },
  {
    id: 'contact',
    title: '13. Contact',
    content: (
      <>
        <p>For questions about these Terms, please contact us at:</p>
        <p>
          <strong>legal@storyverse.app</strong>
        </p>
      </>
    ),
  },
];

const TermsOfService: React.FC = () => {
  return (
    <LegalLayout
      title="Terms of Service"
      sections={sections}
      updatedAt={new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
      backLabel="Back to Home"
    />
  );
};

export default TermsOfService;
